web-socket-poc:
  url: "ws://localhost:8080/ws-poc"
  publish:
    hello: "/app/hello"
  topics:
    greetings: "/topic/greetings"
  scheduled:
    heartbeat:
      enabled: true
      cron: '0 0 12 25 12 MON'